### ISSUE TITLE
Join me on LabB group project

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabB#1]
Join me on LabB group project. Groups can be up to four people total.

**Comment by alternatebow** [comment]
Alright. I'm game

**Comment by karlnicholas** [comment]
Cool, this one looks pretty easy.

**Comment by jillHuang7** [comment]
I am in. But I still working on HW03

**Comment by karlnicholas** [comment]
Ok, cool. I'm going to close the invite since this is a pretty straight forward project, which means there are three of us working on it. Other members please feel free to start your own project/team.

Couple of quick notes:

1: It's a good idea to do a git PULL before you start working to make sure you have the latest updates. Otherwise you may have to merge your work or something. It's much easier to do a PULL and then be sure to Commit and Save after you've done some work.

2: If you work on an issue don't feel you need to do it all. Do as much as you like and then just leave a comment about what's done or left.

 3: Feel free to create any new issues as you see the need.

4: Be patient and considerate with each other. Critique as needed but be professional about it. Don't wait until the last minute to contribute or you may be asked to submit your own work. 

5: Have fun, you guys rock!

**Comment by karlnicholas** [comment]
Also, if you have any questions please feel free to email me directly at karl.nicholas@outlook.com. 

Hopefully your using Eclipse. If so, do File->Import->Git->Projects from Git.

Before you do that go Click on the project here and look on the right side where it says "Git Clone" (something like that) in green.  After clicking on the button copy the SSH git stuff with ^C, or copy this:

git@github.com:CS111C-META-FALL-2016/LabB-Team1.git

Then it will paste automatically into Eclipse during the Import.
